name: 'fintech_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'fintech_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  fintech_analytics:
    # Staging models - materialized as views
    staging:
      +materialized: view
      +schema: staging
      
    # Intermediate models - materialized as views  
    intermediate:
      +materialized: view
      +schema: intermediate
      
    # Mart models - materialized as tables
    marts:
      +materialized: table
      +schema: marts
      
    # Analytics models - materialized as tables with indexes
    analytics:
      +materialized: table
      +schema: analytics
      +post-hook: |
        {% if var('create_indexes', true) %}
          create index if not exists idx_{{ this.name }}_date on {{ this }} (date);
          create index if not exists idx_{{ this.name }}_updated on {{ this }} (updated_at);
        {% endif %}

# Variables
vars:
  # Financial analysis parameters
  short_ma_days: 10      # Short moving average period
  long_ma_days: 30       # Long moving average period
  volatility_window: 20  # Volatility calculation window
  risk_free_rate: 0.045  # Risk-free rate (4.5%)
  
  # Date ranges
  analysis_start_date: '2024-01-01'
  analysis_end_date: '2025-12-31'
  
  # Feature flags
  create_indexes: true
  enable_tests: true