version: 2

sources:
  - name: raw_financial_data
    description: "Raw financial data from various APIs"
    tables:
      - name: stock_prices
        description: "Daily stock price data from multiple sources"
        columns:
          - name: ticker
            description: "Stock ticker symbol"
            tests:
              - not_null
          - name: date
            description: "Trading date"
            tests:
              - not_null
          - name: close_price
            description: "Closing price"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  inclusive: false
          - name: volume
            description: "Trading volume"
            tests:
              - dbt_utils.accepted_range:
                  min_value: 0
                  
      - name: economic_indicators
        description: "Economic indicators from FRED and other sources"
        columns:
          - name: series_id
            description: "Economic series identifier"
            tests:
              - not_null
          - name: date
            description: "Data date"
            tests:
              - not_null
          - name: value
            description: "Indicator value"
            tests:
              - not_null
              
      - name: crypto_prices
        description: "Cryptocurrency price data"
        columns:
          - name: symbol
            description: "Cryptocurrency symbol"
            tests:
              - not_null
          - name: date
            description: "Price date"
            tests:
              - not_null
          - name: price_usd
            description: "Price in USD"
            tests:
              - not_null
              - dbt_utils.accepted_range:
                  min_value: 0
                  inclusive: false
      
      - name: companies
        description: "Company information and metadata"
        columns:
          - name: ticker
            description: "Stock ticker symbol"
            tests:
              - not_null
              - unique
          - name: company_name
            description: "Full company name"
          - name: sector
            description: "Business sector"
          - name: market_cap
            description: "Market capitalization"